### ISSUE TITLE
SAH in code comment, what does it mean?

### ISSUE THREAD

**Issue by glixingxian** [oxfordinternetinstitute/InteractiveVis#59]
if (a==b.source) outgoing[b.target]=n;		//**SAH**
else if (a==b.target) incoming[b.source]=n;		//**SAH**
.........
if (groupByDirection) {
		//**SAH** - Compute intersection for mutual and remove these from incoming/outgoing
		for (e in outgoing) {
			//name=outgoing[e];
			if (e in incoming) {
				mutual[e]=outgoing[e];
				delete incoming[e];
				delete outgoing[e];
			}
		}
    }
I see this **SAH** in the code of main.js of the network/js/main.js file 

Anyone knows what does this abbreviation means? I'm very confused by it and I recommend that every abbr.(abbreviation) is explained by its full notation in the code comment.

Thanks!

**Comment by jthrilly** [comment]
It's simply the initials of one of the authors. Most of our comments were
addressed to each other, so this made things easier to understand.

Though there are some comments, you should consider the code undocumented.

**Comment by computermacgyver** [comment]
> Anyone knows what does this abbreviation means?

As jthrilly has said it simply indicated authorship of some later edits/patches and should be ignored.

>  I recommend that every abbr.(abbreviation) is explained by its full notation in the code comment.

If we had waited to release the code until fully documented, the code would probably never have been released. So, we had to make some compromises to get it released. We are very happy to accept pull requests with changes/improvements.
