### ISSUE TITLE
Create automatically layout

### ISSUE THREAD

**Issue by donc3** [oxfordinternetinstitute/InteractiveVis#61]
Hi! I have a graph in a json file, but it doesn't have any x and y coordinates info. Is there anyway to create the layout automaticallyithout using Gephi?

Thanks and congratulations for this great job.

**Comment by computermacgyver** [comment]
You can use any software you like to generate a layout. We used python and igraph for an earlier application, but anything will do. My recommendation is to create the layout one time and save it in the json file to ensure a consistent user experience, bit it is also possible to layout the graph on the client side with JavaScript. D3 does this and there is a plugin for sigma.js that also does this.
