### ISSUE TITLE
Gephi plugin updated?

### ISSUE THREAD

**Issue by lukewendling** [oxfordinternetinstitute/InteractiveVis#62]
Anyone know if the **Gephi** -> Sigma plugin that uses this lib has been updated somewhere, maybe a fork? The code generated by that plugin uses Sigma 0.1 so its > 4 years old. Thanks!

**Comment by computermacgyver** [comment]
The network related visualization code in this repository is being reworked at https://github.com/oii-nexus/ , but doesn't have all the features of this version yet. The plan is to update the plugin once that code is ready. You might look at https://github.com/Linkurious/linkurious.js as an option (but note its licensing conditions)
