### ISSUE TITLE
How do you actually upload the output file from Gephi?

### ISSUE THREAD

**Issue by lucycol** [oxfordinternetinstitute/InteractiveVis#64]
Hi,
I've used the plugin in Gephi to export my network. I now have a network folder with the various files inside it - how do I actually view the network in a web browser?
Thanks.

**Comment by computermacgyver** [comment]
Open the index.html file in Firefox. Per the readme file, you will not be able to open the files locally with Chrome, but if you upload them to a webserver it will work fine with all browsers.
