### ISSUE TITLE
deprecated files

### ISSUE THREAD

**Issue by Metadatical** [oxfordinternetinstitute/InteractiveVis#66]
Hi, is there a template to fix deprecated file or files? I'm not sure where or exactly how to edit these files. I used Atom js linter and found deprecated files. https://metadatical.github.io/litinfograph/

**Comment by computermacgyver** [comment]
Hi @Metadatical , the main files for the network visualization are at https://github.com/oxfordinternetinstitute/InteractiveVis/tree/master/network . These are over 10 years old and it might be worth just starting fresh at this point. https://www.sigmajs.org/ has a new version and many good examples.

**Comment by Metadatical** [comment]
Hi, thanks for the link. The issue is resolved.
